version: '3'
services:
    kuzushiji-generator:
        build:
            context: ./kuzushiji-generator
            dockerfile: Dockerfile
        volumes:
            - ./kuzushiji-generator/code:/code
            - ~/.config/pulse:/root/.config/pulse
        tty: true
        environment:
            - PULSE_SERVER=docker.for.mac.localhost
    voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
            - 50021:50021
        tty: true
