version: '3'
services:
    kuzushiji-generator:
        build:
            context: ./kuzushiji-generator
            dockerfile: Dockerfile
        environment: 
            TZ: Asia/Tokyo
        volumes:
            - ./kuzushiji-generator/code:/code
        tty: true
    voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
            - 50021:50021
        tty: true
