version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - ./db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tanka
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
    kuzushiji-generator:
        build:
            context: ./kuzushiji-generator
            dockerfile: Dockerfile
        environment:
            TZ: Asia/Tokyo
        volumes:
            - ./kuzushiji-generator/code:/code
        tty: true
